//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloQQPortal.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class helloqqdbEntities : DbContext
    {
        public helloqqdbEntities()
            : base("name=helloqqdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hqq_images> hqq_images { get; set; }
        public virtual DbSet<hqq_log_login> hqq_log_login { get; set; }
        public virtual DbSet<hqq_member> hqq_member { get; set; }
        public virtual DbSet<hqq_member_product> hqq_member_product { get; set; }
        public virtual DbSet<hqq_meta_location> hqq_meta_location { get; set; }
        public virtual DbSet<hqq_product> hqq_product { get; set; }
        public virtual DbSet<hqq_product_faq> hqq_product_faq { get; set; }
        public virtual DbSet<hqq_product_images> hqq_product_images { get; set; }
        public virtual DbSet<hqq_product_review> hqq_product_review { get; set; }
        public virtual DbSet<hqq_product_manual> hqq_product_manual { get; set; }
    }
}
