//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloQQPortal.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class hqq_product_faq
    {
        public int id { get; set; }
        public Nullable<int> product_id { get; set; }
        public string question { get; set; }
        public string answer { get; set; }
        public System.DateTime created_on { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public Nullable<int> modified_by { get; set; }
        public sbyte status { get; set; }
        public sbyte order { get; set; }
    
        public virtual hqq_product hqq_product { get; set; }
    }
}
