//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloQQPortal.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class hqq_product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hqq_product()
        {
            this.hqq_member_product = new HashSet<hqq_member_product>();
            this.hqq_product_faq = new HashSet<hqq_product_faq>();
            this.hqq_product_images = new HashSet<hqq_product_images>();
            this.hqq_product_review = new HashSet<hqq_product_review>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime created_on { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public Nullable<int> modified_by { get; set; }
        public sbyte status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hqq_member_product> hqq_member_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hqq_product_faq> hqq_product_faq { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hqq_product_images> hqq_product_images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hqq_product_review> hqq_product_review { get; set; }
    }
}
