//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloQQPortal.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class hqq_member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hqq_member()
        {
            this.hqq_member_product = new HashSet<hqq_member_product>();
        }
    
        public int id { get; set; }
        public string facebook_id { get; set; }
        public string fullname { get; set; }
        public string facebook_name { get; set; }
        public string picture_url { get; set; }
        public string address { get; set; }
        public string location_code { get; set; }
        public string hometown_code { get; set; }
        public sbyte role { get; set; }
        public Nullable<int> created_by { get; set; }
        public System.DateTime created_on { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public sbyte status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hqq_member_product> hqq_member_product { get; set; }
    }
}
