//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloQQPortal.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class hqq_product_images
    {
        public int id { get; set; }
        public int product_id { get; set; }
        public string filename { get; set; }
        public string path { get; set; }
        public string file_type { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public int created_by { get; set; }
        public sbyte status { get; set; }
        public Nullable<long> length { get; set; }
    
        public virtual hqq_product hqq_product { get; set; }
    }
}
