//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloQQPortal.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class member_product
    {
        public int id { get; set; }
        public int member_id { get; set; }
        public int product_id { get; set; }
        public System.DateTime purchase_date { get; set; }
        public Nullable<System.DateTime> garantee_expired { get; set; }
        public sbyte status { get; set; }
    
        public virtual member member { get; set; }
        public virtual product product { get; set; }
    }
}
