//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloQQPortal.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_review
    {
        public int id { get; set; }
        public Nullable<int> product_id { get; set; }
        public string subject { get; set; }
        public string short_description { get; set; }
        public string review { get; set; }
        public string created_on { get; set; }
        public int created_by { get; set; }
        public sbyte status { get; set; }
    
        public virtual product product { get; set; }
    }
}
